# Generated by Django 5.2.10 on 2026-01-12 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0006_add_price_to_group'),
        ('user', '0008_remove_verification_code_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount in UZS (sum)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='created', max_length=20, verbose_name='Status')),
                ('multicard_uuid', models.CharField(blank=True, help_text='Unique transaction ID from Multicard', max_length=255, null=True, verbose_name='Multicard UUID')),
                ('multicard_invoice_id', models.CharField(blank=True, help_text='Invoice ID sent to Multicard', max_length=255, null=True, verbose_name='Multicard Invoice ID')),
                ('checkout_url', models.URLField(blank=True, help_text='Payment page URL from Multicard', null=True, verbose_name='Checkout URL')),
                ('receipt_url', models.URLField(blank=True, help_text='Payment receipt URL from Multicard', null=True, verbose_name='Receipt URL')),
                ('payment_time', models.DateTimeField(blank=True, help_text='When the payment was completed', null=True, verbose_name='Payment Time')),
                ('payment_method', models.CharField(blank=True, help_text='Payment system used (uzcard, humo, visa, etc.)', max_length=50, null=True, verbose_name='Payment Method')),
                ('card_pan', models.CharField(blank=True, help_text='Masked card number', max_length=16, null=True, verbose_name='Card PAN')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the invoice', null=True, verbose_name='Notes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='education.group', verbose_name='Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='user.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='invoices_student_e04bd2_idx'), models.Index(fields=['group', 'status'], name='invoices_group_i_710475_idx'), models.Index(fields=['multicard_uuid'], name='invoices_multica_a410a1_idx'), models.Index(fields=['status'], name='invoices_status_07776b_idx')],
            },
        ),
    ]
