# Generated by Django 5.2.10 on 2026-01-13 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_create_invoice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Installment number (1 or 2). Null for non-installment invoices.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Installment Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_invoice',
            field=models.ForeignKey(blank=True, help_text='The other installment invoice (for installment 1, links to installment 2, and vice versa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_invoices', to='payment.invoice', verbose_name='Related Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total group price in UZS (sum) - full amount to be paid', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Invoice amount in UZS (sum) - installment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
    ]
