# Generated by Django 5.2.10 on 2026-01-13 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_invoice_installment_number_invoice_related_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='installment_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='related_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Invoice amount in UZS (sum)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
    ]
