# Generated by Django 5.2.10 on 2026-01-20 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_group_total_lessons'),
        ('payment', '0003_remove_invoice_installment_number_and_more'),
        ('user', '0011_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Salary amount in UZS (sum)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('month', models.CharField(help_text='Month in YYYY-MM format (e.g., 2025-01)', max_length=7, verbose_name='Month')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the salary', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salaries',
                'db_table': 'employee_salaries',
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_student_e04bd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_group_i_710475_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoices_multica_a410a1_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='card_pan',
            field=models.CharField(blank=True, help_text='Last 4 digits of the card used for payment', max_length=20, null=True, verbose_name='Card PAN'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (e.g., uzcard, humo, visa, etc.)', max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'Yaratilgan'), ('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('cancelled', 'Bekor qilingan')], default='created', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_time'], name='invoices_payment_ff9765_idx'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='user.employee', verbose_name='Employee'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['month'], name='employee_sa_month_a0f936_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalary',
            index=models.Index(fields=['employee', 'month'], name='employee_sa_employe_92af01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'month')},
        ),
    ]
