# Generated by Django 5.2.10 on 2026-01-20 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_employeesalary_and_more'),
        ('user', '0011_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the salary has been paid', verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when the salary was paid', null=True, verbose_name='Payment Date'),
        ),
        migrations.CreateModel(
            name='MentorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in UZS (sum)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('month', models.CharField(help_text='Month in YYYY-MM format (e.g., 2025-01)', max_length=7, verbose_name='Month')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True, verbose_name='Notes')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether the payment has been made', verbose_name='Is Paid')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when the payment was made', null=True, verbose_name='Payment Date')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_payments', to='user.employee', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentor Payment',
                'verbose_name_plural': 'Mentor Payments',
                'db_table': 'mentor_payments',
                'ordering': ['-month', '-created_at'],
                'indexes': [models.Index(fields=['month'], name='mentor_paym_month_efcffa_idx'), models.Index(fields=['mentor', 'month'], name='mentor_paym_mentor__3628e7_idx')],
                'unique_together': {('mentor', 'month')},
            },
        ),
    ]
