# Generated by Django 6.0.1 on 2026-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speciality_id', models.CharField(choices=[('revit_architecture', 'Revit Architecture'), ('revit_structure', 'Revit Structure'), ('tekla_structure', 'Tekla Structure')], max_length=50, verbose_name='Speciality')),
                ('dates', models.CharField(choices=[('mon_wed_fri', 'Monday - Wednesday - Friday'), ('tue_thu_sat', 'Tuesday - Thursday - Saturday')], max_length=50, verbose_name='Dates')),
                ('time', models.DateTimeField(verbose_name='Lesson Starting Time')),
                ('seats', models.PositiveIntegerField(verbose_name='Maximum Students')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
