# Generated by Django 5.2.10 on 2026-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_add_is_active_field_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Group price in UZS (sum)', max_digits=10, verbose_name='Price'),
        ),
    ]
