# Generated by Django 5.2.10 on 2026-01-13 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_add_price_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_lessons',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of lessons in this group (e.g., 72 lessons). Used for lesson-based payment milestones.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Lessons'),
        ),
    ]
