# Generated by Django 5.2.10 on 2026-01-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers_alter_employee_speciality_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='speciality_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='professionality',
            field=models.CharField(blank=True, help_text='Professional expertise or specialization', max_length=255, null=True, verbose_name='Professionality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
