# Generated by Django 5.2.10 on 2026-01-12 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_id_alter_student_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contract PDF'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+999999999' formatida kiritilishi kerak. Maksimal 13 raqam.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Phone Number'),
        ),
    ]
