# Generated by Django 5.2.10 on 2026-01-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_student_user_and_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract_signed',
            field=models.BooleanField(default=False, help_text='Whether the contract has been electronically signed', verbose_name='Contract Signed'),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_code',
            field=models.CharField(blank=True, help_text='6-digit code for contract signing', max_length=6, null=True, verbose_name='Verification Code'),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Code Expires At'),
        ),
        migrations.AddField(
            model_name='student',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Code Sent At'),
        ),
    ]
