# Generated by Django 5.2.10 on 2026-01-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_verification_code_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verification_code_expires_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verification_code_sent_at',
        ),
    ]
