# Generated by Django 5.2.10 on 2026-01-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_verification_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text="Student full address (tuman, ko'cha, uy)", null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='inn',
            field=models.CharField(blank=True, help_text='Individual Taxpayer Identification Number', max_length=20, null=True, verbose_name='INN'),
        ),
        migrations.AddField(
            model_name='student',
            name='pinfl',
            field=models.CharField(blank=True, help_text='Personal Identification Number of Physical Person', max_length=14, null=True, verbose_name='PINFL'),
        ),
    ]
