# Generated by Django 5.2.10 on 2026-01-14 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_student_address_student_inn_student_pinfl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='inn',
            field=models.CharField(blank=True, help_text='Individual Taxpayer Identification Number (maksimum 9 ta raqam)', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message="INN faqat raqamlardan iborat bo'lishi kerak va maksimum 9 ta belgi bo'lishi kerak.", regex='^\\d{1,9}$')], verbose_name='INN'),
        ),
    ]
