# Generated by Django 5.2.10 on 2026-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_student_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('dasturchi', 'Dasturchi'), ('direktor', 'Direktor'), ('administrator', 'Administrator'), ('sotuv_agenti', 'Sotuv agenti'), ('mentor', 'Mentor'), ('assistent', 'Assistent'), ('buxgalter', 'Buxgalter')], max_length=50, verbose_name='Role'),
        ),
    ]
